% Note that this data plotting code has been generated by ChatGPT 5.5 
% All comments on each line are my own and have been used to demonstrate
% that I understand each line of the MATLAB code. 
%% Read data
T = readtable('digital_equity_values.csv');     % Import the csv file into a table

%% Get unique regions
regions = unique(T.RegNationName);              % This returns the data in the region name column of the table without duplicates

%% Create figure
figure;                                         % Create a figure
hold on;                                        % Keep the plot open and add any more plots to the same axis

% Generate distinct colours
colours = lines(length(regions));               % Generates a different colour for each region

%% Plot each region
for i = 1:length(regions)                       % Iterates through each region to be plotted

    idx = strcmp(T.RegNationName, regions{i});  % Find the index of the rows in the table that correspond to the current region

    scatter( ...                                % The MATLAB function to generated a scatter plot
        T.digital_equity_index(idx), ...                % These are the x-coordinates to be plotted - TO CHANGE
        T.coverage_index(idx), ...            % These are the y-coordinates to be plotted - TO CHANGE
        40, ...                                 % The size of each point to be plotted
        colours(i,:), ...                       % Find the correct colour for the region
        'filled', ...                           % Defines the type of point on the scatter plot
        'DisplayName', regions{i});             % Creates the label for the region to enable the use of a legend

end

%% Format plot
xlabel('Digital Equity Index');                                % This is the x-axis title - TO CHANGE
ylabel('Coverage Index');                                         % This is the y-axis title - TO CHANGE
title('Coverage Index vs Digital Equity Index');         % This is the graph title - TO CHANGE

legend('Location','best');          % Creates a legend and places it wherever is best
grid on;                            % Creates a grid on the plot for easier reading
box on;                             % Creates a box around the axes

hold off;                           % Stops adding more plots to the same figure